
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shifts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shifts_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
